CREATE DATABASE IF NOT EXISTS steps_leaderboard;

USE steps_leaderboard;

CREATE TABLE IF NOT EXISTS teams (
  id VARCHAR(255) PRIMARY KEY,
  name VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS counters (
  id VARCHAR(255) PRIMARY KEY,
  teamId VARCHAR(255) NOT NULL,
  memberName VARCHAR(255) NOT NULL,
  steps INT DEFAULT 0,
  FOREIGN KEY (teamId) REFERENCES teams(id) ON DELETE CASCADE
);